### ISSUE TITLE
Progress meter runs over 100% :)

### ISSUE THREAD

**Issue by jn0** [JakeWharton/mkvdts2ac3#109]
Converting DTS to AC3:
Progress: 126%

**Comment by choekstr** [comment]
Yeah that is known. The way I am calculating the progress it is guessing the %.  So for a workload that doesn't match the predefined workload guestimate it will either end over or under.  The pretty progress had to sacrifice an absolutely accurate % but that isn't the end of the world.

**Comment by jn0** [comment]
Local election magic provides 146% of votes :chart_with_upwards_trend:
