### ISSUE TITLE
Recursive Folder Option

### ISSUE THREAD

**Issue by satheras** [JakeWharton/mkvdts2ac3#123]
Dear Jake/Dear Community,

please could you add an option for a recursive folder processing? I mean that i would like to only specify the parent folder and it browses and processes recursively all directories for mkv files with dts.

That would be really great and makes it easier to use as a cronjob.

Your script became really important after samsung dropped the support for dts on their TVs.

thanks for the great work!

**Comment by JakeWharton** [comment]
Can you do this with `find` and it's `-exec` argument or by piping to `xargs`? The Unix philosophy is such that the script should have a single responsibility and some other tool should be used for searching for files and then for invoking this script.

**Comment by satheras** [comment]
Thats what i did. Thanks!
